mysite/home/urls.py
app_name = 'home'

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.getHomePage, name='home'),
	url(r'^home/$', views.login, name='login')
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls'))
]

mysite/polls/urls.py
app_name = 'polls'

from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	url(r'^logout/$', views.logout, name='logout'),
]

mysite/home/models.py
from django.db import models

# Create your models here.

mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
	
    class Meta:
        permissions = (
            ("can_vote", "Whether a user can vote or not on polls."),
			("can_view", "Can the user view?")
        )
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
	
	# to string method
    def __str__(self):
        return self.question_text
	# Checks if the question was published recently
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
	
    def __str__(self):
	# to string method
        return self.choice_text

mysite/home/views.py
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth import authenticate
from django.template.context_processors import csrf
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.contrib import auth

# ...
def getHomePage(request):
    template = loader.get_template('home/index.html')
    context = {
    }
    return HttpResponse(template.render(context, request))
	
def login(request):
	c = {}
	c.update(csrf(request))
	user = authenticate(username=request.POST.get('username', ''), password=request.POST.get('password', ''))
	if user is not None:
		# the password verified for the user
		auth.login(request, user)
		return HttpResponseRedirect("/polls")
	else:
		# the authentication system was unable to verify the username and password
		return render_to_response("home/failure.html", c)

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.shortcuts import render_to_response
from django.contrib import auth

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

# ...
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def index(request):
	username = request.user.username
	return render_to_response('polls/index.html', {'username': username, 'latest_question_list': Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]})
	
def logout(request):
	auth.logout(request)
	return HttpResponseRedirect("/home")

mysite/home/templates/failure.html
Failure

mysite/home/templates/home/failure.html
Failure

mysite/home/templates/home/index.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <title>Log In</title>
</head>
<body>
    <div class="wrapper">
        <form action="{% url 'home:login' %}" method="post" class="form-signin" >{% csrf_token %}     
            <h2 class="form-signin-heading">Please login</h2>
            <input type="text" class="form-control" name="username" placeholder="Email Address" required="" autofocus="" />
            <input type="password" class="form-control" name="password" placeholder="Password" required=""/>      
            <label class="checkbox">
                <input type="checkbox" value="remember-me" id="rememberMe" name="rememberMe"> Remember me
            </label>
            <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>   
        </form>
    </div>
</body>

mysite/home/templates/home/success.html
Success!

mysite/home/templates/success.html
Success!

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/index.html
<html>
	<head>
    {% load staticfiles %}
     <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
	</head>
	<body>
		{% if username %}
			<p>Hello {{ username }}! <a href="/polls/logout">Logout?</a></p>
		{% endif %}
		{% if latest_question_list %}
			<ul>
			{% for question in latest_question_list %}
				<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
			{% endfor %}
			</ul>
		{% else %}
			<p>No polls are available.</p>
		{% endif %}
	</body>
</html>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>